// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // __MigrationLogCurrent
    public partial class __MigrationLogCurrent
    {
        public System.Guid migration_id { get; set; } // migration_id (Primary key)
        public string script_checksum { get; set; } // script_checksum (Primary key) (length: 64)
        public string script_filename { get; set; } // script_filename (Primary key) (length: 255)
        public System.DateTime complete_dt { get; set; } // complete_dt (Primary key)
        public string applied_by { get; set; } // applied_by (Primary key) (length: 100)
        public byte deployed { get; set; } // deployed (Primary key)

        public __MigrationLogCurrent()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
