// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // __MigrationLog
    public partial class __MigrationLogConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<__MigrationLog>
    {
        public __MigrationLogConfiguration()
            : this("dbo")
        {
        }

        public __MigrationLogConfiguration(string schema)
        {
            ToTable("__MigrationLog", schema);
            HasKey(x => new { x.migration_id, x.complete_dt, x.script_checksum });

            Property(x => x.migration_id).HasColumnName(@"migration_id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.script_checksum).HasColumnName(@"script_checksum").HasColumnType("nvarchar").IsRequired().HasMaxLength(64).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.script_filename).HasColumnName(@"script_filename").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.complete_dt).HasColumnName(@"complete_dt").HasColumnType("datetime2").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.applied_by).HasColumnName(@"applied_by").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.deployed).HasColumnName(@"deployed").HasColumnType("tinyint").IsRequired();
            Property(x => x.version).HasColumnName(@"version").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.package_version).HasColumnName(@"package_version").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.release_version).HasColumnName(@"release_version").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.sequence_no).HasColumnName(@"sequence_no").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
