// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // AppConfigurations
    public partial class AppConfiguration
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public int Version { get; set; } // Version
        public System.DateTime IssuedOn { get; set; } // IssuedOn
        public int SiteId { get; set; } // SiteId
        public bool IsGlobal { get; set; } // IsGlobal

        // Reverse navigation

        /// <summary>
        /// Child AppSettings where [AppSettings].[AppConfigurationId] point to this entity (FK_AppSettings_AppConfigurations)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AppSetting> AppSettings { get; set; } // AppSettings.FK_AppSettings_AppConfigurations
        /// <summary>
        /// Child HealthAndSafetyIcons where [HealthAndSafetyIcon].[AppConfigurationId] point to this entity (FK_HealthAndSafetyIcon_AppConfigurations)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<HealthAndSafetyIcon> HealthAndSafetyIcons { get; set; } // HealthAndSafetyIcon.FK_HealthAndSafetyIcon_AppConfigurations
        /// <summary>
        /// Child SWITypes where [SWITypes].[AppConfigurationId] point to this entity (FK_SWITypes_AppConfigurations)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SWIType> SWITypes { get; set; } // SWITypes.FK_SWITypes_AppConfigurations

        // Foreign keys

        /// <summary>
        /// Parent Site pointed by [AppConfigurations].([SiteId]) (FK_AppConfigurations_Sites)
        /// </summary>
        public virtual Site Site { get; set; } // FK_AppConfigurations_Sites

        public AppConfiguration()
        {
            AppSettings = new System.Collections.Generic.List<AppSetting>();
            HealthAndSafetyIcons = new System.Collections.Generic.List<HealthAndSafetyIcon>();
            SWITypes = new System.Collections.Generic.List<SWIType>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
