// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // AppConfigurations
    public partial class AppConfigurationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AppConfiguration>
    {
        public AppConfigurationConfiguration()
            : this("dbo")
        {
        }

        public AppConfigurationConfiguration(string schema)
        {
            ToTable("AppConfigurations", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Version).HasColumnName(@"Version").HasColumnType("int").IsRequired();
            Property(x => x.IssuedOn).HasColumnName(@"IssuedOn").HasColumnType("datetime2").IsRequired();
            Property(x => x.SiteId).HasColumnName(@"SiteId").HasColumnType("int").IsRequired();
            Property(x => x.IsGlobal).HasColumnName(@"IsGlobal").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Site).WithMany(b => b.AppConfigurations).HasForeignKey(c => c.SiteId).WillCascadeOnDelete(false); // FK_AppConfigurations_Sites
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
