// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // ApprovalActions
    public partial class ApprovalActionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ApprovalAction>
    {
        public ApprovalActionConfiguration()
            : this("dbo")
        {
        }

        public ApprovalActionConfiguration(string schema)
        {
            ToTable("ApprovalActions", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.PermissionId).HasColumnName(@"PermissionId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.ApprovalActions).WithMany(b => b.Permission1).HasForeignKey(c => c.PermissionId).WillCascadeOnDelete(false); // FK_ApprovalActions_ApprovalActions_Permission
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
