// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // ApprovalWorkflows
    public partial class ApprovalWorkflow
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 255)
        public bool CanSelfSign { get; set; } // CanSelfSign
        public bool IsPriority { get; set; } // IsPriority
        public bool IsDefault { get; set; } // IsDefault

        // Reverse navigation

        /// <summary>
        /// Child ApprovalRequests where [ApprovalRequests].[ApprovalWorkflowId] point to this entity (FK_ApprovalRequests_ApprovalWorkflows)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApprovalRequest> ApprovalRequests { get; set; } // ApprovalRequests.FK_ApprovalRequests_ApprovalWorkflows

        public ApprovalWorkflow()
        {
            ApprovalRequests = new System.Collections.Generic.List<ApprovalRequest>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
