// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // ApprovalActions
    public partial class ApprovalAction
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 255)
        public int? PermissionId { get; set; } // PermissionId

        // Reverse navigation

        /// <summary>
        /// Child ApprovalChanges where [ApprovalChanges].[ApprovalActionId] point to this entity (FK_ApprovalChanges_ApprovalAction_ApprovalChanges)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApprovalChanx> ApprovalChanges { get; set; } // ApprovalChanges.FK_ApprovalChanges_ApprovalAction_ApprovalChanges

        public ApprovalAction()
        {
            ApprovalChanges = new System.Collections.Generic.List<ApprovalChanx>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
