// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // ApprovalGroups
    public partial class ApprovalGroup
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 255)
        public int? SiteId { get; set; } // SiteId

        // Reverse navigation

        /// <summary>
        /// Child ApprovalGroupUsers where [ApprovalGroupUsers].[ApprovalGroupId] point to this entity (FK_ApprovalGroupUsers_ApprovalGroup_Users)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApprovalGroupUser> Users { get; set; } // ApprovalGroupUsers.FK_ApprovalGroupUsers_ApprovalGroup_Users
        /// <summary>
        /// Child ApprovalRequests where [ApprovalRequests].[ApprovalGroupId] point to this entity (FK_ApprovalRequests_ApprovalGroup_ApprovalRequests)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApprovalRequest> ApprovalRequests { get; set; } // ApprovalRequests.FK_ApprovalRequests_ApprovalGroup_ApprovalRequests

        public ApprovalGroup()
        {
            Users = new System.Collections.Generic.List<ApprovalGroupUser>();
            ApprovalRequests = new System.Collections.Generic.List<ApprovalRequest>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
