// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // ApprovalRequests
    public partial class ApprovalRequest
    {
        public int Id { get; set; } // Id (Primary key)
        public int DocumentId { get; set; } // DocumentId
        public string RequestedBy { get; set; } // RequestedBy (length: 100)
        public System.DateTime RequestedOn { get; set; } // RequestedOn
        public int ApprovalStatusId { get; set; } // ApprovalStatusId
        public string AssignedApprover { get; set; } // AssignedApprover (length: 100)
        public int ApprovalGroupId { get; set; } // ApprovalGroupId
        public int? ApprovalWorkflowId { get; set; } // ApprovalWorkflowId

        // Reverse navigation

        /// <summary>
        /// Child ApprovalChanges where [ApprovalChanges].[ApprovalRequestId] point to this entity (FK_ApprovalChanges_ApprovalRequest_ApprovalChanges)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApprovalChanx> ApprovalChanges { get; set; } // ApprovalChanges.FK_ApprovalChanges_ApprovalRequest_ApprovalChanges

        // Foreign keys

        /// <summary>
        /// Parent ApprovalGroup pointed by [ApprovalRequests].([ApprovalGroupId]) (FK_ApprovalRequests_ApprovalGroup_ApprovalRequests)
        /// </summary>
        public virtual ApprovalGroup ApprovalGroup { get; set; } // FK_ApprovalRequests_ApprovalGroup_ApprovalRequests
        /// <summary>
        /// Parent ApprovalStatu pointed by [ApprovalRequests].([ApprovalStatusId]) (FK_ApprovalRequests_ApprovalStatus)
        /// </summary>
        public virtual ApprovalStatu ApprovalStatu { get; set; } // FK_ApprovalRequests_ApprovalStatus
        /// <summary>
        /// Parent ApprovalWorkflow pointed by [ApprovalRequests].([ApprovalWorkflowId]) (FK_ApprovalRequests_ApprovalWorkflows)
        /// </summary>
        public virtual ApprovalWorkflow ApprovalWorkflow { get; set; } // FK_ApprovalRequests_ApprovalWorkflows
        /// <summary>
        /// Parent Document pointed by [ApprovalRequests].([DocumentId]) (FK_ApprovalRequests_Documents)
        /// </summary>
        public virtual Document Document { get; set; } // FK_ApprovalRequests_Documents

        public ApprovalRequest()
        {
            ApprovalChanges = new System.Collections.Generic.List<ApprovalChanx>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
