// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // ApprovalChanges
    public partial class ApprovalChanx
    {
        public int Id { get; set; } // Id (Primary key)
        public int? ApprovalRequestId { get; set; } // ApprovalRequestId
        public int? ApprovalActionId { get; set; } // ApprovalActionId
        public string ChangedBy { get; set; } // ChangedBy (length: 100)
        public System.DateTime ChangedOn { get; set; } // ChangedOn
        public string ChangeNotes { get; set; } // ChangeNotes (length: 255)

        // Foreign keys

        /// <summary>
        /// Parent ApprovalAction pointed by [ApprovalChanges].([ApprovalActionId]) (FK_ApprovalChanges_ApprovalAction_ApprovalChanges)
        /// </summary>
        public virtual ApprovalAction ApprovalAction { get; set; } // FK_ApprovalChanges_ApprovalAction_ApprovalChanges
        /// <summary>
        /// Parent ApprovalRequest pointed by [ApprovalChanges].([ApprovalRequestId]) (FK_ApprovalChanges_ApprovalRequest_ApprovalChanges)
        /// </summary>
        public virtual ApprovalRequest ApprovalRequest { get; set; } // FK_ApprovalChanges_ApprovalRequest_ApprovalChanges

        public ApprovalChanx()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
