// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // ApprovalStatus
    public partial class ApprovalStatuConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ApprovalStatu>
    {
        public ApprovalStatuConfiguration()
            : this("dbo")
        {
        }

        public ApprovalStatuConfiguration(string schema)
        {
            ToTable("ApprovalStatus", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.IsApproved).HasColumnName(@"IsApproved").HasColumnType("bit").IsRequired();
            Property(x => x.isPending).HasColumnName(@"isPending").HasColumnType("bit").IsRequired();
            Property(x => x.isRejected).HasColumnName(@"isRejected").HasColumnType("bit").IsRequired();
            Property(x => x.isCancelled).HasColumnName(@"isCancelled").HasColumnType("bit").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
