// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // AppSettings
    public partial class AppSetting
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string Description { get; set; } // Description (length: 255)
        public string Value { get; set; } // Value (length: 1000)
        public int AppConfigurationId { get; set; } // AppConfigurationId

        // Foreign keys

        /// <summary>
        /// Parent AppConfiguration pointed by [AppSettings].([AppConfigurationId]) (FK_AppSettings_AppConfigurations)
        /// </summary>
        public virtual AppConfiguration AppConfiguration { get; set; } // FK_AppSettings_AppConfigurations

        public AppSetting()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
