// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // AppSettings
    public partial class AppSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AppSetting>
    {
        public AppSettingConfiguration()
            : this("dbo")
        {
        }

        public AppSettingConfiguration(string schema)
        {
            ToTable("AppSettings", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Value).HasColumnName(@"Value").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(1000);
            Property(x => x.AppConfigurationId).HasColumnName(@"AppConfigurationId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.AppConfiguration).WithMany(b => b.AppSettings).HasForeignKey(c => c.AppConfigurationId).WillCascadeOnDelete(false); // FK_AppSettings_AppConfigurations
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
