// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // AuthTokens
    public partial class AuthTokenConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AuthToken>
    {
        public AuthTokenConfiguration()
            : this("security")
        {
        }

        public AuthTokenConfiguration(string schema)
        {
            ToTable("AuthTokens", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            Property(x => x.IssuedOn).HasColumnName(@"IssuedOn").HasColumnType("datetime2").IsRequired();
            Property(x => x.ExpiresOn).HasColumnName(@"ExpiresOn").HasColumnType("datetime2").IsRequired();

            // Foreign keys
            HasRequired(a => a.User).WithMany(b => b.AuthTokens).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_AuthTokens_Users
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
