// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // AuthTokens
    public partial class AuthToken
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public System.DateTime IssuedOn { get; set; } // IssuedOn
        public System.DateTime ExpiresOn { get; set; } // ExpiresOn

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [AuthTokens].([UserId]) (FK_AuthTokens_Users)
        /// </summary>
        public virtual User User { get; set; } // FK_AuthTokens_Users

        public AuthToken()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
