// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // DocumentWatchers
    public partial class DocumentWatcher
    {
        public int Id { get; set; } // Id (Primary key)
        public int DocumentId { get; set; } // DocumentId
        public string Username { get; set; } // Username (length: 100)
        public string ClientId { get; set; } // ClientId (length: 255)
        public string Notes { get; set; } // Notes (length: 100)
        public bool Active { get; set; } // Active

        // Foreign keys

        /// <summary>
        /// Parent Document pointed by [DocumentWatchers].([DocumentId]) (FK_DocumentWatchers_Documents)
        /// </summary>
        public virtual Document Document { get; set; } // FK_DocumentWatchers_Documents

        public DocumentWatcher()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
