// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // DocumentFiles
    public partial class DocumentFileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DocumentFile>
    {
        public DocumentFileConfiguration()
            : this("dbo")
        {
        }

        public DocumentFileConfiguration(string schema)
        {
            ToTable("DocumentFiles", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Data).HasColumnName(@"Data").HasColumnType("varbinary(max)").IsOptional();
            Property(x => x.FileSize).HasColumnName(@"FileSize").HasColumnType("int").IsRequired();
            Property(x => x.Hash).HasColumnName(@"Hash").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(1000);
            Property(x => x.ClientHash).HasColumnName(@"ClientHash").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(1000);
            Property(x => x.Timestamp).HasColumnName(@"Timestamp").HasColumnType("datetime2").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
