// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // DocumentTypes
    public partial class DocumentTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DocumentType>
    {
        public DocumentTypeConfiguration()
            : this("dbo")
        {
        }

        public DocumentTypeConfiguration(string schema)
        {
            ToTable("DocumentTypes", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.AllowedFileExt).HasColumnName(@"AllowedFileExt").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.IsString).HasColumnName(@"IsString").HasColumnType("bit").IsRequired();
            Property(x => x.IsBinary).HasColumnName(@"IsBinary").HasColumnType("bit").IsRequired();
            Property(x => x.IsSWI).HasColumnName(@"IsSWI").HasColumnType("bit").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
