// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // DocumentPartLinks
    public partial class DocumentPartLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DocumentPartLink>
    {
        public DocumentPartLinkConfiguration()
            : this("dbo")
        {
        }

        public DocumentPartLinkConfiguration(string schema)
        {
            ToTable("DocumentPartLinks", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PartNumber).HasColumnName(@"PartNumber").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Revision).HasColumnName(@"Revision").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10);
            Property(x => x.ErpSystemId).HasColumnName(@"ErpSystemId").HasColumnType("int").IsOptional();
            Property(x => x.DocumentId).HasColumnName(@"DocumentId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasOptional(a => a.ErpSystem).WithMany(b => b.DocumentPartLinks).HasForeignKey(c => c.ErpSystemId).WillCascadeOnDelete(false); // FK_PartLinks_ErpSystem
            HasRequired(a => a.Document).WithMany(b => b.DocumentPartLinks).HasForeignKey(c => c.DocumentId).WillCascadeOnDelete(false); // FK_PartLinks_Docs
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
