// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // DocumentFiles
    public partial class DocumentFile
    {
        public int Id { get; set; } // Id (Primary key)
        public byte[] Data { get; set; } // Data
        public int FileSize { get; set; } // FileSize
        public string Hash { get; set; } // Hash (length: 1000)
        public string ClientHash { get; set; } // ClientHash (length: 1000)
        public System.DateTime Timestamp { get; set; } // Timestamp

        // Reverse navigation

        /// <summary>
        /// Child Documents where [Documents].[DocumentFileId] point to this entity (FK_Docs_Files)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Document> Documents { get; set; } // Documents.FK_Docs_Files

        public DocumentFile()
        {
            Documents = new System.Collections.Generic.List<Document>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
