// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // DocumentLinks
    public partial class DocumentLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DocumentLink>
    {
        public DocumentLinkConfiguration()
            : this("dbo")
        {
        }

        public DocumentLinkConfiguration(string schema)
        {
            ToTable("DocumentLinks", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DocumentAd).HasColumnName(@"DocumentAd").HasColumnType("int").IsRequired();
            Property(x => x.DocumentBId).HasColumnName(@"DocumentBId").HasColumnType("int").IsRequired();
            Property(x => x.LinkNotes).HasColumnName(@"LinkNotes").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            // Foreign keys
            HasRequired(a => a.Document_DocumentAd).WithMany(b => b.DocumentAd).HasForeignKey(c => c.DocumentAd).WillCascadeOnDelete(false); // FK_DocumentLinks_Documents
            HasRequired(a => a.DocumentB).WithMany(b => b.DocumentB).HasForeignKey(c => c.DocumentBId).WillCascadeOnDelete(false); // FK_DocumentLinks_Documents1
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
