// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // DocumentPartLinks
    public partial class DocumentPartLink
    {
        public int Id { get; set; } // Id (Primary key)
        public string PartNumber { get; set; } // PartNumber (length: 100)
        public string Revision { get; set; } // Revision (length: 10)
        public int? ErpSystemId { get; set; } // ErpSystemId
        public int DocumentId { get; set; } // DocumentId

        // Foreign keys

        /// <summary>
        /// Parent Document pointed by [DocumentPartLinks].([DocumentId]) (FK_PartLinks_Docs)
        /// </summary>
        public virtual Document Document { get; set; } // FK_PartLinks_Docs
        /// <summary>
        /// Parent ErpSystem pointed by [DocumentPartLinks].([ErpSystemId]) (FK_PartLinks_ErpSystem)
        /// </summary>
        public virtual ErpSystem ErpSystem { get; set; } // FK_PartLinks_ErpSystem

        public DocumentPartLink()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
