// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // DocumentChanges
    public partial class DocumentChanx
    {
        public int Id { get; set; } // Id (Primary key)
        public int DocumentId { get; set; } // DocumentId
        public System.DateTime ChangedOn { get; set; } // ChangedOn
        public int ChangedById { get; set; } // ChangedById
        public string ChangeNotes { get; set; } // ChangeNotes (length: 255)

        // Foreign keys

        /// <summary>
        /// Parent Document pointed by [DocumentChanges].([DocumentId]) (FK_DocumentChanges_Documents)
        /// </summary>
        public virtual Document Document { get; set; } // FK_DocumentChanges_Documents
        /// <summary>
        /// Parent User pointed by [DocumentChanges].([ChangedById]) (FK_DocumentChanges_Users)
        /// </summary>
        public virtual User User { get; set; } // FK_DocumentChanges_Users

        public DocumentChanx()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
