// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // DocumentTypes
    public partial class DocumentType
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 255)
        public string AllowedFileExt { get; set; } // AllowedFileExt (length: 255)
        public bool IsString { get; set; } // IsString
        public bool IsBinary { get; set; } // IsBinary
        public bool IsSWI { get; set; } // IsSWI

        // Reverse navigation

        /// <summary>
        /// Child Documents where [Documents].[DocumentTypeId] point to this entity (FK_Documents_DocumentTypes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Document> Documents { get; set; } // Documents.FK_Documents_DocumentTypes

        public DocumentType()
        {
            Documents = new System.Collections.Generic.List<Document>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
