// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // DocumentChanges
    public partial class DocumentChanxConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DocumentChanx>
    {
        public DocumentChanxConfiguration()
            : this("dbo")
        {
        }

        public DocumentChanxConfiguration(string schema)
        {
            ToTable("DocumentChanges", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DocumentId).HasColumnName(@"DocumentId").HasColumnType("int").IsRequired();
            Property(x => x.ChangedOn).HasColumnName(@"ChangedOn").HasColumnType("datetime2").IsRequired();
            Property(x => x.ChangedBy).HasColumnName(@"ChangedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.ChangeNotes).HasColumnName(@"ChangeNotes").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);

            // Foreign keys
            HasRequired(a => a.Document).WithMany(b => b.DocumentChanges).HasForeignKey(c => c.DocumentId).WillCascadeOnDelete(false); // FK_DocumentChanges_Documents
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
