// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // ErpSystem
    public partial class ErpSystem
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 255)

        // Reverse navigation

        /// <summary>
        /// Child DocumentPartLinks where [DocumentPartLinks].[ErpSystemId] point to this entity (FK_PartLinks_ErpSystem)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DocumentPartLink> DocumentPartLinks { get; set; } // DocumentPartLinks.FK_PartLinks_ErpSystem

        public ErpSystem()
        {
            DocumentPartLinks = new System.Collections.Generic.List<DocumentPartLink>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
