// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // HealthAndSafetyIcon
    public partial class HealthAndSafetyIcon
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (Primary key) (length: 255)
        public string Image { get; set; } // Image
        public int AppConfigurationId { get; set; } // AppConfigurationId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent AppConfiguration pointed by [HealthAndSafetyIcon].([AppConfigurationId]) (FK_HealthAndSafetyIcon_AppConfigurations)
        /// </summary>
        public virtual AppConfiguration AppConfiguration { get; set; } // FK_HealthAndSafetyIcon_AppConfigurations

        public HealthAndSafetyIcon()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
