// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // HealthAndSafetyIcon
    public partial class HealthAndSafetyIconConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<HealthAndSafetyIcon>
    {
        public HealthAndSafetyIconConfiguration()
            : this("dbo")
        {
        }

        public HealthAndSafetyIconConfiguration(string schema)
        {
            ToTable("HealthAndSafetyIcon", schema);
            HasKey(x => new { x.Id, x.Name, x.AppConfigurationId });

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Image).HasColumnName(@"Image").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.AppConfigurationId).HasColumnName(@"AppConfigurationId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.AppConfiguration).WithMany(b => b.HealthAndSafetyIcons).HasForeignKey(c => c.AppConfigurationId).WillCascadeOnDelete(false); // FK_HealthAndSafetyIcon_AppConfigurations
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
