// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // Notifications
    public partial class Notification
    {
        public int Id { get; set; } // Id (Primary key)
        public string Username { get; set; } // Username (length: 100)
        public string Message { get; set; } // Message (length: 1000)
        public string Type { get; set; } // Type (length: 100)
        public bool Dismissed { get; set; } // Dismissed
        public System.DateTime SentOn { get; set; } // SentOn

        public Notification()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
