// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // Permissions
    public partial class Permission
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 255)
        public string Description { get; set; } // Description (length: 255)

        // Reverse navigation

        /// <summary>
        /// Child ApprovalActions where [ApprovalActions].[PermissionId] point to this entity (FK_ApprovalActions_ApprovalActions_Permission)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApprovalAction> Permission1 { get; set; } // ApprovalActions.FK_ApprovalActions_ApprovalActions_Permission
        /// <summary>
        /// Child RolePermissions where [RolePermissions].[PermissionId] point to this entity (FK_RolePermissions_Permissions)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RolePermission> RolePermissions { get; set; } // RolePermissions.FK_RolePermissions_Permissions

        public Permission()
        {
            Permission1 = new System.Collections.Generic.List<ApprovalAction>();
            RolePermissions = new System.Collections.Generic.List<RolePermission>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
