// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // Sites
    public partial class Site
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 255)
        public string SiteADSecurityGroup { get; set; } // SiteADSecurityGroup (length: 100)
        public int? AppSecurityCompanyId { get; set; } // AppSecurityCompanyId

        // Reverse navigation

        /// <summary>
        /// Child AppConfigurations where [AppConfigurations].[SiteId] point to this entity (FK_AppConfigurations_Sites)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AppConfiguration> AppConfigurations { get; set; } // AppConfigurations.FK_AppConfigurations_Sites
        /// <summary>
        /// Child SWIMasterSitePermissions where [SWIMasterSitePermissions].[SiteId] point to this entity (FK_SWIMasterSitePermissions_Sites)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SWIMasterSitePermission> SWIMasterSitePermissions { get; set; } // SWIMasterSitePermissions.FK_SWIMasterSitePermissions_Sites

        public Site()
        {
            AppConfigurations = new System.Collections.Generic.List<AppConfiguration>();
            SWIMasterSitePermissions = new System.Collections.Generic.List<SWIMasterSitePermission>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
