// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // StandardTools
    public partial class StandardTool
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (Primary key) (length: 255)
        public string Image { get; set; } // Image (Primary key)
        public bool HasCarePoint { get; set; } // HasCarePoint (Primary key)
        public string CarePoint { get; set; } // CarePoint (length: 255)
        public System.Guid? SWIId { get; set; } // SWIId

        // Foreign keys

        /// <summary>
        /// Parent SWIMaster pointed by [StandardTools].([SWIId]) (FK_StandardTools_SWIMasters)
        /// </summary>
        public virtual SWIMaster SWIMaster { get; set; } // FK_StandardTools_SWIMasters

        public StandardTool()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
