// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // SWIMasters
    public partial class SWIMaster
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title (length: 255)
        public int SWINumber { get; set; } // SWINumber
        public bool IsPublic { get; set; } // IsPublic
        public int CreatedById { get; set; } // CreatedById
        public System.DateTime CreatedOn { get; set; } // CreatedOn
        public int SWITypeId { get; set; } // SWITypeId

        // Reverse navigation

        /// <summary>
        /// Child StandardTools where [StandardTools].[SWIId] point to this entity (FK_StandardTools_SWIMasters)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StandardTool> StandardTools { get; set; } // StandardTools.FK_StandardTools_SWIMasters
        /// <summary>
        /// Child SWIMasterSitePermissions where [SWIMasterSitePermissions].[SWIMasterId] point to this entity (FK_SWIMasterSitePermissions_SWIMasters)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SWIMasterSitePermission> SWIMasterSitePermissions { get; set; } // SWIMasterSitePermissions.FK_SWIMasterSitePermissions_SWIMasters
        /// <summary>
        /// Child SWIRevisions where [SWIRevisions].[MasterId] point to this entity (FK_SWIRevisions_SWIMasters)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SWIRevision> SWIRevisions { get; set; } // SWIRevisions.FK_SWIRevisions_SWIMasters

        // Foreign keys

        /// <summary>
        /// Parent SWIType pointed by [SWIMasters].([SWITypeId]) (FK_SWIMasters_SWITypes)
        /// </summary>
        public virtual SWIType SWIType { get; set; } // FK_SWIMasters_SWITypes
        /// <summary>
        /// Parent User pointed by [SWIMasters].([CreatedById]) (FK_SWIMasters_CreatedBy_SWIMastersCreated)
        /// </summary>
        public virtual User CreatedBy { get; set; } // FK_SWIMasters_CreatedBy_SWIMastersCreated

        public SWIMaster()
        {
            StandardTools = new System.Collections.Generic.List<StandardTool>();
            SWIMasterSitePermissions = new System.Collections.Generic.List<SWIMasterSitePermission>();
            SWIRevisions = new System.Collections.Generic.List<SWIRevision>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
