// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // SWIMasters
    public partial class SWIMasterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SWIMaster>
    {
        public SWIMasterConfiguration()
            : this("swi")
        {
        }

        public SWIMasterConfiguration(string schema)
        {
            ToTable("SWIMasters", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Title).HasColumnName(@"Title").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255);
            Property(x => x.SWINumber).HasColumnName(@"SWINumber").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IsPublic).HasColumnName(@"IsPublic").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime2").IsRequired();
            Property(x => x.SWITypeId).HasColumnName(@"SWITypeId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.SWIType).WithMany(b => b.SWIMasters).HasForeignKey(c => c.SWITypeId).WillCascadeOnDelete(false); // FK_SWIMasters_SWITypes
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
