// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // SWIRevisions
    public partial class SWIRevision
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public int RevisionNumber { get; set; } // RevisionNumber
        public bool Released { get; set; } // Released
        public System.Guid MasterId { get; set; } // MasterId
        public string AppVersion { get; set; } // AppVersion (length: 50)
        public System.DateTime CreatedOn { get; set; } // CreatedOn
        public System.DateTime ModifiedOn { get; set; } // ModifiedOn
        public int? DocumentId { get; set; } // DocumentId

        // Foreign keys

        /// <summary>
        /// Parent Document pointed by [SWIRevisions].([DocumentId]) (FK_SWIRevisions_Documents)
        /// </summary>
        public virtual Document Document { get; set; } // FK_SWIRevisions_Documents
        /// <summary>
        /// Parent SWIMaster pointed by [SWIRevisions].([MasterId]) (FK_SWIRevisions_SWIMasters)
        /// </summary>
        public virtual SWIMaster SWIMaster { get; set; } // FK_SWIRevisions_SWIMasters

        public SWIRevision()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
