// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RC.SWI.Entities
{

    // UserRoles
    public partial class UserRole
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public int? RoleId { get; set; } // RoleId

        // Foreign keys

        /// <summary>
        /// Parent Role pointed by [UserRoles].([RoleId]) (FK_UserRoles_Roles)
        /// </summary>
        public virtual Role Role { get; set; } // FK_UserRoles_Roles
        /// <summary>
        /// Parent User pointed by [UserRoles].([UserId]) (FK_UserRoles_Users)
        /// </summary>
        public virtual User User { get; set; } // FK_UserRoles_Users

        public UserRole()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
